### PR TITLE
Issue fixes #6:

### LINKED ISSUE #6: Calculated input voltage not providing calibration value
I tried this out on an Arduino Uno - Mega328p

```
--- MENU ---
	R to read Vcc
	L to load calibration from EEPROM
	S to store calibration into EEPROM
	C to clear calibration from EEPROM
	dddd (4 digits) to calibrate for mV
	A to print EEPROM calibration start address (length 3)
	Adddd (4 digits) to set EEPROM calibration start address (length 3)
	H prints this help
Calculated input voltage is 5120mV
Real bandgap voltage is 1101mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
```
Sending R again to the serial again, presented me with 0mv for everything

```
Calculated input voltage is 0mV
Real bandgap voltage is 0mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
Calibrating for Vcc 0mV
Calibration value is 0
Real bandgap voltage is 0mV
```

Ideas? The code looks correct, and works when using the readVCC() from the secret multimeter.

### PR DESCRIPTION
**Pull request by cuteboi**
stop parsing Carriage Return / Line Feed

### CODE REVIEW

**Comment by cuteboi** [comment]
**EEPROMCalibration**
Before Optimizing memory:

```
Sketch uses 4810 bytes (14%) of program storage space. Maximum is 32256 bytes.
Global variables use 850 bytes (41%) of dynamic memory, leaving 1198 bytes for local variables. Maximum is 2048 bytes.
```
After:
```
Sketch uses 4944 bytes (15%) of program storage space. Maximum is 32256 bytes.
Global variables use 262 bytes (12%) of dynamic memory, leaving 1786 bytes for local variables. Maximum is 2048 bytes.
```

**AnalogAndVoltage**
Before Optimization:
```
Sketch uses 2390 bytes (7%) of program storage space. Maximum is 32256 bytes.
Global variables use 270 bytes (13%) of dynamic memory, leaving 1778 bytes for local variables. Maximum is 2048 bytes.
```
After:
```
Sketch uses 2452 bytes (7%) of program storage space. Maximum is 32256 bytes.
Global variables use 192 bytes (9%) of dynamic memory, leaving 1856 bytes for local variables. Maximum is 2048 bytes.
```

**Review by rlogiacco — APPROVED** [review]

**Review by rlogiacco — CHANGES_REQUESTED** [review]
I don't think this helps, even if I understand the memory usage is very high, those are only examples and we should aim at readability and portability rather than optimization: `F()` doesn't make sense outside of the Arduino world...

**Comment by rlogiacco** [comment]
I'm willing to accept your pull request if you remove/revert commit 90f0a15

**Comment by cuteboi** [comment]
Ok, how about now? reverted the optimizations.  And you're right, it doesn't make too much sense outside of Atmel based platforms.  But it is applicable to all other ATTINY/ATMEGA, which is what this code base was intended for.

Thanks for the input at least.

**Review by rlogiacco — APPROVED** [review]

**Pull request merged**
